title: Gerry Eisenhaur
author:
  name: Gerry Eisenhaur
  email: gerry.eisenhaur@gmail.com
  github: gerry
  twitter: gerryeisenhaur 

production_url : http://gerry.github.io/
markdown: redcarpet
highlighter: pygments
