title: Gerry Eisenhaur
author:
  name: Gerry Eisenhaur
  email: gerry.eisenhaur@gmail.com
  github: gerry
  twitter: gerryeisenhaur 

production_url : http://gerry.github.io/
markdown: redcarpet2 
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
